### ISSUE TITLE
Markdown file content duplication

### ISSUE THREAD

**Issue by mroberts1** [crisrojas/Zettels#4]
I exported files from Bear to the /content/ directory in my Hugo repo, and the files displayed on localhost, but the content of each .md file was duplicated 5 times on the web page for each file. Any idea why this would be? I created an _index.md file in /content/ but it's empty - I wasn't sure what frontmatter I should put it, or whether I needed to.

**Comment by crisrojas** [comment]
Hi Martin,

Have you tried launching the server disabling fast rendering? as:

` hugo server --disableFastRender`

That should do the work 🙂

For the _index.md, that will be the entry point of the website, you don't need to use any frontmater, you can even create that file inside Bear (just create a note and give it the `_index` title). You could take a look at what my index file looks like here: https://notes.cristian.lat.

Hope that helps.
