### ISSUE TITLE
render of "page" failed - error calling Concat:  slice

### ISSUE THREAD

**Issue by hieu6** [crisrojas/Zettels#5]
I added the the `layouts/partials` for backlinks and wikilinks to my [personal hugo blog](https://github.com/hieu6/hieu6.github.io/tree/main/layouts/partials)

I added this bit to `layouts/index.html`.

```
{{ define "main" }}
	{{ partial "wikilinks.html" . }}
{{ end }}
```

for good measure, I also added `{{ partial "wikilinks.html" . }}` at the top of `themes/[theme name]/layouts/_default/single.html`

_tho I am realizing just now that I may not be able to adjust the theme directly if I `git clone`'d it into my repo (?)_

---
**trying it out:**
in this [post](https://github.com/hieu6/hieu6.github.io/blob/main/content/blog/first-post.md) I first tried using [[wikilinks]] to call a page using [[file-name.md]] or [[yaml title]] and neither worked to link the pages. 

I know I'm missing something. Could someone point me in the right direction?

---

it is true. I am a noob and not sure what I'm doing but trying my best to follow the docs. 

Would anyone here who has attempted and succeeded at implementing this into their own theme be able to assist me with this?

You have my gratitude!

**Comment by crisrojas** [comment]
Hi hieu, thank you for the interest in the project.

I tried to locally run your blog but I'm not able due to submodule problems with the theme you're using (I'm probably making something the wrong way). I will retry this weekend and tell you more about that, for now, what I could tell:


- In order to use the wikilinks on post, you should use the "wikilinks" partial on a "single.html" template, but ...
- The partials you have added shouldn't work because you're using a theme and Hugo only uses one layout folder to render the pages, either one: the layout folder of the theme or the root layout folder. If you want to use those partials with that specific theme you should put them in the theme repo (if you own the repo, if not you must fork the theme and apply the modifications, which will make you lose any theme update from the original author)
- Your index.html has some redundancies, your partial "wikilinks.html" will render the transformed ".Content" of the markdown file. On index.html there's a call to that partial and immediately after that there's a {{ .Content }} call.


Hope that helps :)

**Comment by crisrojas** [comment]
I tried to serve your hugo project at home, but I wasn't able to run it.  This is the workflow I tried:

1. git clone
2. git submodule init
3. git submodule update

It fails at two with the following error: 

"fatal: No url found for submodule path 'themes/archie' in .gitmodules"

Maybe you could provide some steps to run your project from a different environment that yours?

**Comment by hieu6** [comment]
Cris, thank you for your help with this. theme archie was cloned directly into the themes folder, not as a submodule. The problem is more likely that I broke something in the templates while messing around and I can't remember what it is! Will start over and try again 😅 

I love the changes to your theme 'zettels' since it was first released a few months ago! I'd like to use this going forward. 

Steps:
1. `hugo new site test26` --> https://github.com/hieu6/test26
2. `git submodule add https://github.com/crisrojas/zettels.git themes/zettels`
3. set `theme = "zettels"` in `config.toml`
4. hugo serve

There are some error messages:

```shell 
# i added line breaks to make it easier to read

ERROR 2021/09/25 22:49:47 render of "page" failed: 
"/Users/HIEU/site/test26/themes/zettels/layouts/_default/baseof.html:48:62": 
execute of template failed: template: _default/single.html:48:62: executing 
"_default/single.html" at <resources.Concat>: error calling Concat: 
slice []interface {} not supported in concat

ERROR 2021/09/25 22:49:47 render of "home" failed: 
"/Users/HIEU/site/test26/themes/zettels/layouts/_default/baseof.html:48:62": 
execute of template failed: template: index.html:48:62: executing "index.html" 
at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat

Error: Error building site: failed to render pages: render of "page" failed: 
"/Users/HIEU/site/test26/themes/zettels/layouts/_default/baseof.html:48:62": 
execute of template failed: template: _default/single.html:48:62: executing 
"_default/single.html" at <resources.Concat>: error calling Concat: 
slice []interface {} not supported in concat
```


Below are lines 48:62 of `_default/baseof.html`

```golang
{{ $main := slice $themeVariables $styles $syntax | resources.Concat "css/main.css" | minify | fingerprint }}
	
	
	<link rel="stylesheet" href="{{ $main.Permalink }}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
	
	{{ $turbolinks := resources.Get "js/turbolinks.js" }}
	{{ $thumbnails := resources.Get "js/thumbnails.js" }}
	{{ $search     := resources.Get "js/search.js" }}
	
	{{ $.Scratch.Set "jslibs" slice }}
	{{ $libs := slice "js/turbolinks.js" "js/thumbnails.js" "js/search.js" }}
	
	{{ range $libs }}
	{{ $.Scratch.Add "jslibs" (resources.Get . ) }}
```

I took a peek and found that `assets/css` contains `style.scss` so I changed line 48 to the following:

`{{ $main := slice $themeVariables $styles $syntax | resources.Concat "css/style.scss" | minify | fingerprint }}`

that didn't work so I changed it back to `main.css`.... *flails, flaps arms* I don't know what I'm doing, ha! I checked the hugo docs re: slice but don't understand why terminal is upset.

What do you think, @crisrojas?
